CREATE SEQUENCE ads_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE category_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE chats_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE comments_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE favorites_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE images_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE messages_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE tokens_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE users_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE ads (
 is_active BOOLEAN NOT NULL,
 views INTEGER NOT NULL,
 category_id BIGINT,
 id BIGINT NOT NULL,
 price BIGINT NOT NULL,
 users_id BIGINT,
 created VARCHAR(255),
 description VARCHAR(255),
 title VARCHAR(255),
 PRIMARY KEY (id)
);

CREATE TABLE category (
 id BIGINT NOT NULL,
 name VARCHAR(255),
 path VARCHAR(255),
 PRIMARY KEY (id)
);

CREATE TABLE chats (
 ad_id BIGINT,
 id BIGINT NOT NULL,
 message_id BIGINT UNIQUE,
 owner_id BIGINT,
 receiver_id BIGINT,
 PRIMARY KEY (id)
);

CREATE TABLE comments (
 rating INTEGER NOT NULL,
 convicted_id BIGINT,
 id BIGINT NOT NULL,
 creator_id BIGINT,
 created VARCHAR(255),
 text VARCHAR(255),
 PRIMARY KEY (id)
);

CREATE TABLE favorites (
 ad_id BIGINT,
 id BIGINT NOT NULL,
 user_id BIGINT,
 PRIMARY KEY (id)
);

CREATE TABLE images (
 ad_id BIGINT,
 id BIGINT NOT NULL,
 image_bytes BYTEA,
 PRIMARY KEY (id)
);

CREATE TABLE messages (
 chat_id BIGINT,
 id BIGINT NOT NULL,
 user_id BIGINT,
 content VARCHAR(255),
 data VARCHAR(255),
 PRIMARY KEY (id)
);

CREATE TABLE tokens (
 id BIGINT NOT NULL,
 user_id BIGINT UNIQUE,
 device_token VARCHAR(255),
 PRIMARY KEY (id)
);

CREATE TABLE users (
 rating_all INTEGER NOT NULL,
 rating_num INTEGER NOT NULL,
 id BIGINT NOT NULL,
 address VARCHAR(255),
 email VARCHAR(255),
 name VARCHAR(255),
 password VARCHAR(255),
 phone VARCHAR(255),
 username VARCHAR(255),
 avatar BYTEA,
 PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS ads
 ADD CONSTRAINT FK_ads_category FOREIGN KEY (category_id) REFERENCES category;

ALTER TABLE IF EXISTS ads
 ADD CONSTRAINT FK_ads_user FOREIGN KEY (users_id) REFERENCES users;

ALTER TABLE IF EXISTS chats
 ADD CONSTRAINT FK_chats_ad FOREIGN KEY (ad_id) REFERENCES ads;

ALTER TABLE IF EXISTS chats
 ADD CONSTRAINT FK_chats_message FOREIGN KEY (message_id) REFERENCES messages;

ALTER TABLE IF EXISTS chats
 ADD CONSTRAINT FK_chats_owner FOREIGN KEY (owner_id) REFERENCES users;

ALTER TABLE IF EXISTS chats
 ADD CONSTRAINT FK_chats_receiver FOREIGN KEY (receiver_id) REFERENCES users;

ALTER TABLE IF EXISTS comments
 ADD CONSTRAINT FK_comments_convicted FOREIGN KEY (convicted_id) REFERENCES users;

ALTER TABLE IF EXISTS comments
 ADD CONSTRAINT FK_comments_creator FOREIGN KEY (creator_id) REFERENCES users;

ALTER TABLE IF EXISTS favorites
 ADD CONSTRAINT FK_favorites_ad FOREIGN KEY (ad_id) REFERENCES ads;

ALTER TABLE IF EXISTS favorites
 ADD CONSTRAINT FK_favorites_user FOREIGN KEY (user_id) REFERENCES users;

ALTER TABLE IF EXISTS images
 ADD CONSTRAINT FK_images_ad FOREIGN KEY (ad_id) REFERENCES ads;

ALTER TABLE IF EXISTS messages
 ADD CONSTRAINT FK_messages_chat FOREIGN KEY (chat_id) REFERENCES chats;

ALTER TABLE IF EXISTS messages
 ADD CONSTRAINT FK_messages_user FOREIGN KEY (user_id) REFERENCES users;

ALTER TABLE IF EXISTS tokens
 ADD CONSTRAINT FK_tokens_user FOREIGN KEY (user_id) REFERENCES users;