INSERT INTO category(id,name,path) VALUES (1,'Техника', 'electronics');
INSERT INTO category(id,name,path) VALUES (2,'Обувь', 'shoes');
INSERT INTO category(id,name,path) VALUES (3,'Одежда', 'clothing');
INSERT INTO category(id,name,path) VALUES (4,'Спорт', 'sports');
INSERT INTO category(id,name,path) VALUES (5,'Продукты', 'food');
INSERT INTO category(id,name,path) VALUES (6,'Учебные материалы', 'books');
INSERT INTO category(id,name,path) VALUES (7,'Услуги', 'service');
INSERT INTO category(id,name,path) VALUES (8,'Хобби', 'hobby');
INSERT INTO category(id,name,path) VALUES (9,'Работа', 'work');
INSERT INTO category(id,name,path) VALUES (10,'Акксесуары', 'accessories');
INSERT INTO category(id,name,path) VALUES (11,'Поездки', 'trips');