name: board_client
description: "Client side for my app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  flutter_bloc: ^8.1.6
  grpc: ^4.0.0
  protobuf: ^3.1.0
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  shared_preferences: ^2.3.2
  form_field_validator: ^1.1.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  dio: ^5.4.3+1
  http: ^1.2.1
  animated_text_kit: ^4.2.2
  flutter_image_compress: ^2.3.0
  flutter_rating_bar: ^4.0.1
  firebase_messaging: ^15.0.4
  firebase_auth: ^5.3.3
  firebase_core: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/