name: board_client
description: "Client side for my app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  flutter_bloc: ^8.1.5
  go_router: ^14.1.2
  google_fonts: ^6.2.1
  carousel_slider: ^4.2.1
  grpc: ^3.2.4
  protobuf: ^3.1.0
  shared_preferences: ^2.2.3
  form_field_validator: ^1.1.0
  flutter_multi_formatter: ^2.12.8
  image_picker: ^1.1.2
  archive: ^3.6.1
  flutter_image_compress: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/