version: '3.9'

services:
  boardserver:
    container_name: boardserver
    image: boardserver:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_URL: ${DB_URL}
        PG_USER: ${PG_USER}
        PG_PASSWORD: ${PG_PASSWORD}
    ports:
      - "9090:9090"
      - "8080:8080"
    depends_on:
      - db
      - zipkin
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/postgres
      - SPRING_DATASOURCE_USER=boarduser
      - SPRING_DATASOURCE_PASSWORD=boardpass
      - SPRING_APPLICATION_NAME=microservice
      - SERVER_PORT=8080
      - SPRING_ZIPKIN_BASE_URL=http://host.docker.internal:9411
      - SPRING_REDIS_HOST=host.docker.internal
    volumes:
      - board-data:/var/lib/boardserver/data
    networks: [ "microservices" ]

  zipkin:
    image: openzipkin/zipkin:latest
    restart: always
    container_name: zipkin
    ports:
      - "9411:9411"
    networks: [ "microservices" ]

  db:
    container_name: db
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: boarduser
      POSTGRES_PASSWORD: boardpass
    volumes:
      - db-data:/var/lib/postgresql/data
    networks: [ "microservices" ]

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks: [ "microservices" ]

volumes:
  db-data:
  board-data:
  pgadmin-data:

networks:
  microservices:
    name: microservices


