spring:
  application:
    name: Board server
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  server:
    port: 8080
  grpc:
    server:
      port: 9090