spring:
  application:
    name: boardserver
  datasource:
    url: ${DB_URL}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  server:
    port: 8080
  grpc:
    server:
      port: 9090