spring:
  application:
    name: boardserver
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USER}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  server:
    port: 8080
  grpc:
    reflection-service-enabled: true
    server:
      port: 9090
  flyway:
    enabled: true
    baselineOnMigrate: true

management:
  tracing:
    enabled: true
    tags:
      service.name: boardserver
  endpoints:
    web:
      exposure:
        include: tracing

otel:
  traces:
    exporter:
      otlp:
        endpoint: "http://localhost:4317"
    zipkin:
      service.name: boardserver
      enabled: true
      endpoint: http://localhost:9411/api/v2/spans

jwt:
  secret:
    access: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
    refresh: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==

firebase:
  secretKey: 8ClknOAu9iNb/DE0CWYjo2u54qbEg6i6NSgJdTgYf80=
